### ISSUE TITLE
Unable to trim video that is captured from camera

### ISSUE THREAD

**Issue by umarpazir11** [anthorlop/VideoTrimmer#2]

**Comment by SamKapoor** [comment]
E/isoparser: DefaultMp4SampleList:java.io.IOException: ftruncate failed: EINVAL (Invalid argument)
                                                                        at java.nio.FileChannelImpl.map(FileChannelImpl.java:244)
                                                                        at com.googlecode.mp4parser.FileDataSourceImpl.map(FileDataSourceImpl.java:62)
                                                                        at com.googlecode.mp4parser.BasicContainer.getByteBuffer(BasicContainer.java:223)
                                                                        at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList$SampleImpl.asByteBuffer(DefaultMp4SampleList.java:204)
                                                                        at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList$SampleImpl.writeTo(DefaultMp4SampleList.java:181)
                                                                        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder$InterleaveChunkMdat.getBox(DefaultMp4Builder.java:762)
                                                                        at com.googlecode.mp4parser.BasicContainer.writeContainer(BasicContainer.java:216)
                                                                        at com.selfiesoapbox.video.videocut.VideoRecorderedPlayerActivity.trimVideo(VideoRecorderedPlayerActivity.java:481)
                                                                        at com.selfiesoapbox.video.videocut.VideoRecorderedPlayerActivity.access$700(VideoRecorderedPlayerActivity.java:46)
                                                                        at com.selfiesoapbox.video.videocut.VideoRecorderedPlayerActivity$PostTrimAsynkTask.doInBackground(VideoRecorderedPlayerActivity.java:528)
                                                                        at com.selfiesoapbox.video.videocut.VideoRecorderedPlayerActivity$PostTrimAsynkTask.doInBackground(VideoRecorderedPlayerActivity.java:509)
                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:841)
                                                                     Caused by: libcore.io.ErrnoException: ftruncate failed: EINVAL (Invalid argument)
                                                                        at libcore.io.Posix.ftruncate(Native Method)
                                                                        at libcore.io.BlockGuardOs.ftruncate(BlockGuardOs.java:102)
                                                                        at java.nio.FileChannelImpl.map(FileChannelImpl.java:236)
                                                                        at com.googlecode.mp4parser.FileDataSourceImpl.map(FileDataSourceImpl.java:62) 
                                                                        at com.googlecode.mp4parser.BasicContainer.getByteBuffer(BasicContainer.java:223) 
                                                                        at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList$SampleImpl.asByteBuffer(DefaultMp4SampleList.java:204) 
                                                                        at com.googlecode.mp4parser.authoring.samples.DefaultMp4SampleList$SampleImpl.writeTo(DefaultMp4SampleList.java:181) 
                                                                        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder$InterleaveChunkMdat.getBox(DefaultMp4Builder.java:762) 
                                                                        at com.googlecode.mp4parser.BasicContainer.writeContainer(BasicContainer.java:216) 
                                                                        at com.selfiesoapbox.video.videocut.VideoRecorderedPlayerActivity.trimVideo(VideoRecorderedPlayerActivity.java:481) 
                                                                        at com.selfiesoapbox.video.videocut.VideoRecorderedPlayerActivity.access$700(VideoRecorderedPlayerActivity.java:46) 
                                                                        at com.selfiesoapbox.video.videocut.VideoRecorderedPlayerActivity$PostTrimAsynkTask.doInBackground(VideoRecorderedPlayerActivity.java:528) 
                                                                        at com.selfiesoapbox.video.videocut.VideoRecorderedPlayerActivity$PostTrimAsynkTask.doInBackground(VideoRecorderedPlayerActivity.java:509) 
                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                        at java.lang.Thread.run(Thread.java:841)
